<a href="https://colab.research.google.com/github/yashshinde0607/DS_LAB_SE_B_67/blob/main/DSLAB3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
# Take input from the user
print("Enter the elements of the 3x3 matrix row-wise:")

matrix = []
for i in range(3):
    row = list(map(int, input(f"Enter row {i+1}: ").split()))
    matrix.append(row)

# Assign matrix elements
a, b, c = matrix[0]
d, e, f = matrix[1]
g, h, i = matrix[2]

# Calculate determinant
determinant = (
    a * (e*i - f*h)
    - b * (d*i - f*g)
    + c * (d*h - e*g)
)

# Display result
print("\nMatrix:")
for row in matrix:
    print(row)

print("\nDeterminant of the matrix:")
print(determinant)


Enter the elements of the 3x3 matrix row-wise:
Enter row 1: 1 2 3
Enter row 2: 8 5 9
Enter row 3: 4 7 6

Matrix:
[1, 2, 3]
[8, 5, 9]
[4, 7, 6]

Determinant of the matrix:
51


In [9]:
import numpy as np

# Take input from the user
print("Enter the elements of the 3x3 matrix row-wise:")

elements = []
for i in range(3):
    row = list(map(float, input(f"Enter row {i+1} (3 values separated by space): ").split()))
    elements.append(row)

# Create NumPy array
matrix = np.array(elements)

# Compute determinant
determinant = np.linalg.det(matrix)

# Display results
print("\nMatrix:")
print(matrix)

print("\nDeterminant of the matrix:")
print(determinant)


Enter the elements of the 3x3 matrix row-wise:
Enter row 1 (3 values separated by space): 1 2 3
Enter row 2 (3 values separated by space): 8 5 9
Enter row 3 (3 values separated by space): 4 7 6

Matrix:
[[1. 2. 3.]
 [8. 5. 9.]
 [4. 7. 6.]]

Determinant of the matrix:
51.0


In [11]:
# Finding inverse of the matrix without using function
print("Enter the elements of the 3x3 matrix row-wise:")

m = []
for i in range(3):
    m.append(list(map(float, input(f"Row {i+1}: ").split())))

a, b, c = m[0]
d, e, f = m[1]
g, h, i = m[2]

# Determinant
det = a*(e*i - f*h) - b*(d*i - f*g) + c*(d*h - e*g)
print("\nDeterminant:", det)

if det == 0:
    print("Inverse does not exist (determinant is zero).")
else:
    inv = [
        [(e*i - f*h)/det, (c*h - b*i)/det, (b*f - c*e)/det],
        [(f*g - d*i)/det, (a*i - c*g)/det, (c*d - a*f)/det],
        [(d*h - e*g)/det, (b*g - a*h)/det, (a*e - b*d)/det]
    ]

    print("\nInverse of the matrix:")
    for row in inv:
        print(row)



Enter the elements of the 3x3 matrix row-wise:
Row 1: 2 3 6
Row 2: 2 3 2
Row 3: 2 4 8

Determinant: 8.0

Inverse of the matrix:
[2.0, 0.0, -1.5]
[-1.5, 0.5, 1.0]
[0.25, -0.25, 0.0]


In [3]:
# Finding inverse of the matrix with using function
import numpy as np

print("Enter elements of 3x3 matrix:")
A = np.array([[float(input(f"a[{i+1}][{j+1}]: "))
               for j in range(3)] for i in range(3)])

print("\nInverse of the matrix:")
print(np.linalg.inv(A))


Enter elements of 3x3 matrix:
a[1][1]: 2
a[1][2]: 3
a[1][3]: 6
a[2][1]: 2
a[2][2]: 3
a[2][3]: 2
a[3][1]: 2
a[3][2]: 4
a[3][3]: 8

Inverse of the matrix:
[[ 2.    0.   -1.5 ]
 [-1.5   0.5   1.  ]
 [ 0.25 -0.25 -0.  ]]


In [ ]:
# Take input from the user
print("Solve a system of 2 equations of the form: a1*x + b1*y = c1 and a2*x + b2*y = c2")

a1 = float(input("Enter a1: "))
b1 = float(input("Enter b1: "))
c1 = float(input("Enter c1: "))

a2 = float(input("Enter a2: "))
b2 = float(input("Enter b2: "))
c2 = float(input("Enter c2: "))

# Determinant of coefficient matrix
det_A = a1*b2 - a2*b1

if det_A == 0:
    print("The system has no unique solution (determinant is zero).")
else:
    # Using Cramer's Rule
    det_x = c1*b2 - c2*b1
    det_y = a1*c2 - a2*c1

    x = det_x / det_A
    y = det_y / det_A

    print("\nSolution of the system:")
    print(f"x = {x}, y = {y}")


Solve a system of 2 equations of the form: a1*x + b1*y = c1 and a2*x + b2*y = c2
Enter a1: 2
Enter b1: 3
Enter c1: 10
Enter a2: 4
Enter b2: 5
Enter c2: 20

Solution of the system:
x = 5.0, y = -0.0


In [ ]:
import numpy as np

print("Solve a system of 2 equations of the form: a1*x + b1*y = c1 and a2*x + b2*y = c2")

# Take input from the user
a1 = float(input("Enter a1: "))
b1 = float(input("Enter b1: "))
c1 = float(input("Enter c1: "))

a2 = float(input("Enter a2: "))
b2 = float(input("Enter b2: "))
c2 = float(input("Enter c2: "))

# Create coefficient matrix A and constants vector B
A = np.array([[a1, b1],
              [a2, b2]])
B = np.array([c1, c2])

# Check determinant
det_A = np.linalg.det(A)

if det_A == 0:
    print("The system has no unique solution (determinant is zero).")
else:
    # Solve the system
    solution = np.linalg.solve(A, B)
    x, y = solution
    print("\nSolution of the system:")
    print(f"x = {x}, y = {y}")
5

Solve a system of 2 equations of the form: a1*x + b1*y = c1 and a2*x + b2*y = c2
Enter a1: 2
Enter b1: 3
Enter c1: 10
Enter a2: 4
Enter b2: 5
Enter c2: 20

Solution of the system:
x = 5.0, y = 0.0


5