<a href="https://colab.research.google.com/github/yashshinde0607/DS_LAB_SE_B_67/blob/main/DSLAB3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Take input from the user
print("Enter the elements of the 3x3 matrix row-wise:")

matrix = []
for i in range(3):
    row = list(map(int, input(f"Enter row {i+1}: ").split()))
    matrix.append(row)

# Assign matrix elements
a, b, c = matrix[0]
d, e, f = matrix[1]
g, h, i = matrix[2]

# Calculate determinant
determinant = (
    a * (e*i - f*h)
    - b * (d*i - f*g)
    + c * (d*h - e*g)
)

# Display result
print("\nMatrix:")
for row in matrix:
    print(row)

print("\nDeterminant of the matrix:")
print(determinant)


Enter the elements of the 3x3 matrix row-wise:
Enter row 1: 1 0 0
Enter row 2: 0 1 0
Enter row 3: 0 0 1

Matrix:
[1, 0, 0]
[0, 1, 0]
[0, 0, 1]

Determinant of the matrix:
1


In [ ]:
import numpy as np

# Take input from the user
print("Enter the elements of the 3x3 matrix row-wise:")

elements = []
for i in range(3):
    row = list(map(float, input(f"Enter row {i+1} (3 values separated by space): ").split()))
    elements.append(row)

# Create NumPy array
matrix = np.array(elements)

# Compute determinant
determinant = np.linalg.det(matrix)

# Display results
print("\nMatrix:")
print(matrix)

print("\nDeterminant of the matrix:")
print(determinant)


Enter the elements of the 3x3 matrix row-wise:
Enter row 1 (3 values separated by space): 1 0 4
Enter row 2 (3 values separated by space): 5 0 9
Enter row 3 (3 values separated by space): 6 0 8

Matrix:
[[1. 0. 4.]
 [5. 0. 9.]
 [6. 0. 8.]]

Determinant of the matrix:
0.0


In [22]:
# Take input from the user
print("Enter the elements of the 3x3 matrix row-wise:")

matrix = []
for i in range(3):
    row = list(map(float, input(f"Enter row {i+1}: ").split()))
    matrix.append(row)

# Assign elements
a, b, c = matrix[0]
d, e, f = matrix[1]
g, h, i = matrix[2]

# Calculate determinant
det = (a*(e*i - f*h) -
       b*(d*i - f*g) +
       c*(d*h - e*g))

print("\nDeterminant:", det)

# Find inverse of determinant
if det == 0:
    print("Inverse of determinant does not exist (determinant is zero).")
else:
    inv_det = 1 / det
    print("Inverse of the Matrix:", inv_det)


Enter the elements of the 3x3 matrix row-wise:
Enter row 1: 1 0 0
Enter row 2: 4 5 6
Enter row 3: 7 5 9

Determinant: 15.0
Inverse of the Matrix: 0.06666666666666667


In [ ]:
import numpy as np

# Take input from the user
print("Enter the elements of the 3x3 matrix row-wise:")

matrix = []
for i in range(3):
    row = list(map(float, input(f"Enter row {i+1}: ").split()))
    matrix.append(row)

# Convert to NumPy array
matrix = np.array(matrix)

# Calculate determinant
det = np.linalg.det(matrix)
print("\nMatrix:")
print(matrix)
print("\nDeterminant:", det)

# Find inverse of determinant
if det == 0:
    print("Inverse of determinant does not exist (determinant is zero).")
else:
    inv_det = 1 / det
    print("Inverse of the Matrix:", inv_det)


Enter the elements of the 3x3 matrix row-wise:
Enter row 1: 4 5 6
Enter row 2: 7 8 9 
Enter row 3: 5 3 6

Matrix:
[[4. 5. 6.]
 [7. 8. 9.]
 [5. 3. 6.]]

Determinant: -15.0
Inverse of the Matrix: -0.06666666666666667


In [25]:
# Take input from the user
print("Solve a system of 2 equations of the form: a1*x + b1*y = c1 and a2*x + b2*y = c2")

a1 = float(input("Enter a1: "))
b1 = float(input("Enter b1: "))
c1 = float(input("Enter c1: "))

a2 = float(input("Enter a2: "))
b2 = float(input("Enter b2: "))
c2 = float(input("Enter c2: "))

# Determinant of coefficient matrix
det_A = a1*b2 - a2*b1

if det_A == 0:
    print("The system has no unique solution (determinant is zero).")
else:
    # Using Cramer's Rule
    det_x = c1*b2 - c2*b1
    det_y = a1*c2 - a2*c1

    x = det_x / det_A
    y = det_y / det_A

    print("\nSolution of the system:")
    print(f"x = {x}, y = {y}")


Solve a system of 2 equations of the form: a1*x + b1*y = c1 and a2*x + b2*y = c2
Enter a1: 2
Enter b1: 3
Enter c1: 10
Enter a2: 4
Enter b2: 5
Enter c2: 20

Solution of the system:
x = 5.0, y = -0.0


In [24]:
import numpy as np

print("Solve a system of 2 equations of the form: a1*x + b1*y = c1 and a2*x + b2*y = c2")

# Take input from the user
a1 = float(input("Enter a1: "))
b1 = float(input("Enter b1: "))
c1 = float(input("Enter c1: "))

a2 = float(input("Enter a2: "))
b2 = float(input("Enter b2: "))
c2 = float(input("Enter c2: "))

# Create coefficient matrix A and constants vector B
A = np.array([[a1, b1],
              [a2, b2]])
B = np.array([c1, c2])

# Check determinant
det_A = np.linalg.det(A)

if det_A == 0:
    print("The system has no unique solution (determinant is zero).")
else:
    # Solve the system
    solution = np.linalg.solve(A, B)
    x, y = solution
    print("\nSolution of the system:")
    print(f"x = {x}, y = {y}")
5

Solve a system of 2 equations of the form: a1*x + b1*y = c1 and a2*x + b2*y = c2
Enter a1: 2
Enter b1: 3
Enter c1: 10
Enter a2: 4
Enter b2: 5
Enter c2: 20

Solution of the system:
x = 5.0, y = 0.0


5